apiVersion: v1
kind: Service
metadata:
  name: plunker-legacy-www
  labels:
    app: plunker-legacy-www
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: plunker-legacy-www
  type: LoadBalancer
  loadBalancerIP: 104.197.139.153
